trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  artifactName: 'functionapp-build'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the Function App'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish the Function App'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*FunctionApp2.csproj'  # Replace with your actual project name
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: false

# ✅ Copy native .so libraries into the publish/bin directory
- script: |
    echo "Copying native libraries..."
    mkdir -p $(Build.ArtifactStagingDirectory)/publish/bin
    cp bin/*.so* $(Build.ArtifactStagingDirectory)/publish/bin/
  displayName: 'Copy native libraries to publish/bin'

# ✅ Zip the final package
- task: ArchiveFiles@2
  displayName: 'Create deployment zip'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
    replaceExistingArchive: true

# ✅ Publish the zip as an artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container'
